CREATE TABLE IF NOT EXISTS contents (
 id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, description TEXT NOT NULL,
 body TEXT NOT NULL, author TEXT NOT NULL, type TEXT NOT NULL CHECK(type IN ('ESTUDO','Pregação','ARTIGO')),
 imageUrl TEXT, createdAt INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS songs (
 id INTEGER PRIMARY KEY AUTOINCREMENT, number INTEGER NOT NULL UNIQUE CHECK(number > 0),
 title TEXT NOT NULL, category TEXT NOT NULL, lyrics TEXT NOT NULL, author TEXT
);
CREATE TABLE IF NOT EXISTS daily_messages (
 id INTEGER PRIMARY KEY AUTOINCREMENT, message TEXT NOT NULL, bibleReference TEXT NOT NULL, date TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS bible_books (
 id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, abbreviation TEXT NOT NULL,
 testament TEXT NOT NULL CHECK(testament IN ('OLD_TESTAMENT','NEW_TESTAMENT')),
 bookOrder INTEGER NOT NULL UNIQUE CHECK(bookOrder > 0), chapterCount INTEGER NOT NULL CHECK(chapterCount > 0)
);
CREATE TABLE IF NOT EXISTS bible_verses (
 id INTEGER PRIMARY KEY AUTOINCREMENT, bookId INTEGER NOT NULL REFERENCES bible_books(id) ON DELETE RESTRICT,
 chapter INTEGER NOT NULL CHECK(chapter > 0), verse INTEGER NOT NULL CHECK(verse > 0), text TEXT NOT NULL,
 UNIQUE(bookId, chapter, verse)
);
CREATE TABLE IF NOT EXISTS metadata (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS contents_created ON contents(createdAt DESC);
